import Head from "next/head";
import { useState } from "react";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {AiFillHome, AiFillGithub, AiOutlineMail, AiOutlinePhone,  AiFillInstagram, AiFillDatabase } from "react-icons/ai";
import { IoLogoNodejs } from "react-icons/io";
import { BsLightbulbFill } from "react-icons/bs";
import { SiMongodb, SiTypescript, SiNextdotjs } from "react-icons/si";
import Image from "next/image";
import deved from "../../public/dev-ed-wave-1.png";
import ecommerce from "../../public/ecommerce.png";
import secret from "../../public/secret.png";
import movieFight from "../../public/movieFight.png";
import maze from "../../public/maze.png";
import ledger from "../../public/ledger.png";
import unsplash from "../../public/unsplash.png";
import country from "../../public/country.png";
import design from "../../public/design.png";
import code from "../../public/code.png";
import wave from "../../public/dev-ed-wave.png";
import consulting from "../../public/consulting.png";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [showPdf, setShowPdf] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  const colors = ["#ba7672", "#ccc", "#6cf", "#eba13a"];

  const openPdf = () => {
    setShowPdf(true);
    window.open(
      "https://drive.google.com/file/d/1V7gTJ62d3kSnF1o6k7R6uDswBAr6ICpQ/view?usp=sharing",
      "_blank"
    );
  };

  function animateCircles(event) {
    var circle = document.createElement("div");
    circle.setAttribute("class", "circle");
    document.body.appendChild(circle);

    circle.style.left = event.clientX + "px";
    circle.style.top = event.clientY + "px";
    var color = colors[Math.floor(Math.random() * colors.length)];

    circle.style.transition = "all 0.5s linear 0s";
    circle.style.borderColor = color;

    circle.style.left = circle.offsetLeft - 20 + "px";
    circle.style.top = circle.offsetTop - 20 + "px";

    circle.style.width = "50px";
    circle.style.height = "50px";
    circle.style.borderWidth = "5px";
    circle.style.opacity = "0";

    setTimeout(() => {
      circle.remove();
    }, 200);
  }
  // document.onmousemove = animateCircles;

  if (typeof document !== "undefined") {
    let element = (document.onmousemove = animateCircles);

    // Manipulating the DOM here
  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl border-2 p-2 rounded dark:text-white">
              SG
            </h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? <BsLightbulbFill
                  onClick={() => {
                    setDarkMode(!darkMode),
                      console.log(`dark mode checked: ${darkMode}`);
                  }}
                  className="cursor-pointer text-3xl hover:text-teal-600 dark:hover:text-yellow-500"/> :
                <BsFillMoonStarsFill
                  onClick={() => {
                    setDarkMode(!darkMode),
                      console.log(`dark mode checked: ${darkMode}`);
                  }}
                  className="cursor-pointer text-2xl dark:hover:text-teal-600 hover:text-yellow-500"
                />}
              </li>
              <li>
                <a
                 
                  onClick={openPdf}
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Saugat Giri
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Front end developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Web and App developer providing services for programming needs.
              Join me down below and let's get kraken!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Link href="https://github.com/saugat-15">
                <AiFillGithub
                  
                  className="hover:text-teal-600"
                />
              </Link>
              <Link href="https://www.linkedin.com/in/saugat-giri-66011513b/">
                <AiFillLinkedin
                 
                  className="hover:text-teal-600"
                />
              </Link>
              <Link href="https://www.instagram.com/saugat_giri/">
                <AiFillInstagram
                  
                  className="hover:text-teal-600"
                />
              </Link>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image alt ="" src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Overview</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              As a driven web developer, I am dedicated to delivering
              high-quality results and am constantly seeking new challenges. My
              skills in the latest technologies, combined with a passion for
              problem-solving, make me a valuable asset to any team. Let's work
              together to create innovative and effective web solutions.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:text-white flex-1">
              <Image alt="" src={code} width={130} height={170} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <div className="flex justify-center gap-4">
                <SiNextdotjs className="mt-1" />
                <p className="mb-4"> React/Next.js</p>
              </div>
              <div className="flex justify-center gap-4">
                <IoLogoNodejs className="mt-1" />
                <p className="mb-4"> Node.js</p>
              </div>
              <div className="flex justify-center gap-4">
                <AiFillDatabase className="mt-1" />
                <p className="mb-4"> Databases: Relational/Non-relational</p>
              </div>
              <div className="flex justify-center gap-4">
                <SiTypescript className="mt-1" />
                <p className="mb-4"> TypeScript</p>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:text-white flex-1">
              <Image
                alt=""
                src={design}
                onClick={() => console.log("imageClicked")}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600 ">Design Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-white">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-white">Illustrator</p>
              <p className="text-gray-800 py-1 dark:text-white">Figma</p>
              <p className="text-gray-800 py-1 dark:text-white">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:text-white flex-1">
              <Image alt="" src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Check out some of my projects:
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Link href="https://moviefightapi.netlify.app/">
                <Image
                  alt=""
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={movieFight}
                />
              </Link>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Tech stack: OMDB API | HTML | CSS | JS</p>
            </div>
            <div className="basis-1/3 flex-1">
              <Link href="https://ecommerce-node.netlify.app/">
                <Image
                  alt=""
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={ecommerce}
                />
              </Link>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Tech stack: REACT/REDUX | NODE.JS | MONGO | CLOUDINARY | MULTER | BCRYPT/JWT</p>
            </div>
            <div className="basis-1/3 flex-1">
              <Link href="https://matterjslib.netlify.app/">
                <Image
                  alt=""
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={maze}
                />
              </Link>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Tech stack: MATTER.JS (2D rigid body physics engine written in JavaScript) | HTML | CSS | JS</p>
            </div>
            <div className="basis-1/3 flex-1">
              <Link href="https://projectedgeledger.netlify.app/#home">
                <Image
                  alt=""
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={ledger}
                />
              </Link>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Tech stack: HTML | CSS | JS</p>
            </div>
            <div className="basis-1/3 flex-1">
              <Link href="https://messagesharing.netlify.app/">
                <Image
                  alt=""
                  className="rounded-lg object-fit"
                  width={50}
                  height={50}
                  layout="responsive"
                  src={secret}
                />
              </Link>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Tech stack: Encryption | HTML | CSS | JS</p>
            </div>
            <div className="basis-1/3 flex-1">
              <Link href="https://unsplash.com/@saugat151">
                <Image
                  alt=""
                  className="rounded-lg object-fit"
                  width={50}
                  height={50}
                  layout="responsive"
                  src={unsplash}
                />
              </Link>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Photography Profile</p>
            </div>
          </div>
        </section>

        {/* Contact me */}
        <section>
        <div className="text-center shadow-xl p-10 rounded-xl dark:text-white flex-1">
              {/* <Image alt="" src={code} width={130} height={170} /> */}
              <h3 className="text-3xl font-medium p-8 ">
                Reach Out to me..
              </h3>
              
              <div className="flex justify-center gap-4">
                <AiOutlineMail className="mt-1" />
                <p className="mb-4"> saugatgiri15@gmail.com</p>
              </div>
              <div className="flex justify-center gap-4">
                <AiOutlinePhone className="mt-1" />
                <p className="mb-4">+61452654702</p>
              </div>
              <div className="flex justify-center gap-4">
                <AiFillHome className="mt-1" />
                <p className="mb-4">Melbourne, VIC</p>
              </div>
            </div>
        </section>
      </main>
    </div>
  );
}
